### ISSUE TITLE
Setup geoserver.myclimateservice.eu

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/docker-geoserver#1]
Create new GeoServer and PostGis Containers based on https://github.com/kartoza/docker-geoserver for geoserver.myclimateservice.eu.

**Comment by Itsman-AT** [comment]
@p-a-s-c-a-l : So, this one is then obsolote after the creation of the containers above?

https://geonode.myclimateservice.eu/geoserver/clarity/wms?service=WMS&request=getCapabilities

**Comment by p-a-s-c-a-l** [comment]
Yes, since there seems no need for [GeoNode](https://github.com/clarity-h2020/docker-geonode) anymore, we'll use a plain GeoServer + PostGis container without the GeoNode overhead and possible security issues.

**Comment by Itsman-AT** [comment]
I also understand, that we shall put all the available data (that has been asked for, last time this noon https://github.com/orgs/clarity-h2020/teams/data-processing-team) on this database and publish it on this new Geoserver, right?

**Comment by p-a-s-c-a-l** [comment]
> I also understand, that we shall put all the available data (that has been asked for, last time this noon https://github.com/orgs/clarity-h2020/teams/data-processing-team) on this database and publish it on this new Geoserver, right?

Yes, IMHO the data produced by @clarity-h2020/data-processing-team should eventually be made available on the AIT server in the GeoServer and Postgres Containers so that the database can be directly accessed by EMIKAT.

**Comment by Itsman-AT** [comment]
@p-a-s-c-a-l :  As I see, you already put a docker-compose file here:

https://github.com/clarity-h2020/docker-geoserver/blob/dev/docker-compose.yml

I guess, I shall use this one? The howto you posted above suggests to configure one, so I will be using yours. Only proble is, that 

`git clone git://github.com/kartoza/docker-geoserver`

give me an error at the moment:

![grafik](https://user-images.githubusercontent.com/41750112/49279875-f3ee2400-f488-11e8-961f-58d8a78415a1.png)

**Comment by Itsman-AT** [comment]
@p-a-s-c-a-l : BTW, is it save to exchange OpenJDK with the Oracle one on our system? Is Java used somewhere else at the moment?

**Comment by p-a-s-c-a-l** [comment]
There is no need to clone the repo as the image is available on docker hub (see [getting-the-image](https://github.com/kartoza/docker-geoserver#getting-the-image). I'll setup the geoserver and postgis containers in /docker/600-geoserver and include host-mounted volumes in [duplicity](https://github.com/clarity-h2020/docker-duplicity) backups.


> BTW, is it save to exchange OpenJDK with the Oracle one on our system? Is Java used somewhere else at the moment?

I don't understand this question. there is no need to install oracle/open jdk directly on the machine since all services runs in containers! If you want to customise and locally build the kartoza/docker-geoserver image, e.g. to [use oracle JDK](https://github.com/kartoza/docker-geoserver#building-with-oracle-jdk), we should discuss this offline.

**Comment by p-a-s-c-a-l** [comment]
Done.

@clarity-h2020/data-processing-team refer to docker/readme.md for information on how to access geoserver and geoserver-postgis

**Comment by Itsman-AT** [comment]
@p-a-s-c-a-l : I was under the impression, that I shall do this Geoserver Docker install from your first post in this thread, since it was asigned to me. If this is done now, I will not proceed in this direction.
